import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#290055",
        "primary-fixed": "#8bfb91",
        error: "#ffb4ab",
        "primary-container": "#34a547",
        primary: "#6fdd78",
        "on-primary-fixed-variant": "#005319",
        "secondary-fixed-dim": "#a2c9ff",
        "on-background": "#dfe2eb",
        "surface-variant": "#31353c",
        "outline-variant": "#3e4a3d",
        background: "#10141a",
        "on-surface-variant": "#becab9",
        "tertiary-container": "#a979eb",
        "on-primary-container": "#00320b",
        "on-tertiary-container": "#3c0077",
        "secondary-fixed": "#d3e4ff",
        "error-container": "#93000a",
        "on-surface": "#dfe2eb",
        "tertiary-fixed-dim": "#d8baff",
        "on-secondary-fixed": "#001c38",
        "surface-container-lowest": "#0a0e14",
        "surface-bright": "#353940",
        secondary: "#a2c9ff",
        "on-primary-fixed": "#002106",
        "on-tertiary-fixed-variant": "#5b2b9a",
        "primary-fixed-dim": "#6fdd78",
        "secondary-container": "#0071c7",
        "on-primary": "#00390e",
        "tertiary-fixed": "#eddcff",
        surface: "#10141a",
        "inverse-primary": "#006e23",
        "on-secondary-fixed-variant": "#004882",
        "surface-dim": "#10141a",
        "inverse-on-surface": "#2d3137",
        "inverse-surface": "#dfe2eb",
        "surface-container-high": "#262a31",
        "on-secondary": "#00315c",
        "surface-container-highest": "#31353c",
        "surface-container": "#1c2026",
        "surface-tint": "#6fdd78",
        outline: "#889484",
        "surface-container-low": "#181c22",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#f0f4ff",
        "on-error": "#690005",
        tertiary: "#d8baff",
        "on-tertiary": "#430882",
        border: "rgba(255,255,255,0.1)",
        muted: {
          DEFAULT: "rgba(255,255,255,0.05)",
          foreground: "#becab9",
        },
        card: {
          DEFAULT: "rgba(22,27,34,0.7)",
          foreground: "#dfe2eb",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "story-safe-area": "24px",
        "container-max": "1200px",
        "stack-sm": "8px",
        gutter: "16px",
        "stack-xl": "64px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "display-xl": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "mono-label": ["JetBrains Mono"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "display-xl": ["80px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "900" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-code": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-label": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 8s ease-in-out infinite",
        shimmer: "shimmer 3s linear infinite",
        grow: "slide-in 1.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(2deg)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "slide-in": {
          from: { width: "0" },
          to: { width: "var(--final-width)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        grid: "radial-gradient(circle at 2px 2px, rgba(111,221,120,0.15) 1px, transparent 0)",
      },
      backgroundSize: {
        grid: "40px 40px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
